### ISSUE TITLE
Special Direct Object cannot be handled

### ISSUE THREAD

**Issue by achyutjoshi** [ishikaarora4/Aspect-Sentiment-Analysis-on-Amazon-Reviews#9]
"I love them"

**Comment by achyutjoshi** [comment]
Eg2 : "I am very happy with my purchase"

**Comment by djSharma7** [comment]
The Spacy rules are not extracting right aspect modifiers for many reviews i have checked.
@achyutjoshi 
Even i have gone through your blog https://achyutjoshi.github.io/aspect_extraction/clustering
I am a beginner and I'm exploring things..
I have checked your code, you have implemented 7 rules.. i was trying it and did not get  accurate results with those rules..
Can you please help me..

**Comment by djSharma7** [comment]
[sample_data.txt](https://github.com/ishikaarora/Aspect-Sentiment-Analysis-on-Amazon-Reviews/files/4541056/sample_data.txt)

**Comment by djSharma7** [comment]
I have attached a sample data file containing somewhere around 10 rows ..
It is not extracting the accurate aspects .
The attached file has three rows.. product_id , review_id, review_body ..
Since could not upload tsv format here so in txt format

**Comment by achyutjoshi** [comment]
Hey @djSharma7 ! Sorry, we are not maintaining this repository anymore. However, do keep in mind that the rules-based model is a heuristic and it is bound to fail in some cases. An unsupervised ML approach would help you there. Good luck and do reach out if you want to have any meta discussion! :)
